### ISSUE TITLE
Error: TypeError: require(...) is not a function

### ISSUE THREAD

**Issue by unbugx** [csstools/postcss-plugins#409]
Hello there! I use bunch of different postcss plugins:
"postcss": "8.4.5",
"postcss-calc": "8.2.2",
"postcss-color-function": "4.1.0",
"postcss-composes": "0.1.0",
"postcss-custom-media": "8.0.0",
"postcss-custom-properties": "12.1.3",
"postcss-custom-selectors": "6.0.0",
"postcss-flexbugs-fixes": "5.0.2",
"postcss-for": "2.1.1",
"postcss-import": "14.0.2",
"postcss-inline-rtl": "0.9.8",
"postcss-loader": "6.2.1",
"postcss-media-minmax": "5.0.0",
"postcss-nested": "5.0.1",
"postcss-nesting": "10.1.2",
"postcss-partial-import": "4.1.0",
"postcss-pseudoelements": "5.0.0",
"postcss-selector-matches": "4.0.0",
"postcss-selector-not": "4.0.1",
"postcss-url": "10.1.3",

 and when I try to update postcss-selector-not to version 5 I have this error:

```
Module build failed (from ../node_modules/postcss-loader/dist/cjs.js):
TypeError: require(...) is not a function
```

It works ok with version 4.0.1

**Comment by romainmenke** [comment]
Hi @unbugx 

We just migrated `postcss-selector-not` to the mono repo here and published a new release (v6.0.0).

This version should resolve this issue.
Can you verify this?
