### ISSUE TITLE
TypeScript error after upgrading postcss-preset-env from 9.3.0 to 9.4.0 

### ISSUE THREAD

**Issue by doberkofler** [csstools/postcss-plugins#1295]
### Bug description

scripts-ts/bundle.ts:25:30 - error TS7016: Could not find a declaration file for module 'postcss-preset-env'. '/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/postcss-preset-env/dist/index.cjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/postcss-preset-env` if it exists or add a new declaration (.d.ts) file containing `declare module 'postcss-preset-env';`

25 import postcssPresetEnv from 'postcss-preset-env';
                                ~~~~~~~~~~~~~~~~~~~~


### Actual Behavior

_No response_

### Expected Behavior

_No response_

### Can you reproduce it with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

N/A

### `npx` Output

_No response_

### Extra config

_No response_

### What plugin are you experiencing this issue on?

PostCSS Preset Env

### Plugin version

9.4.0

### What OS are you experiencing this on?

macOS

### Node Version

20.11.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @doberkofler,
Thank you for reaching out about this.

In the past we had an incorrect setup and config which made it so that types were broken for everyone but that TypeScript silently ignored all this.
We fixed this by only providing types for es modules.

Since your project is commonjs you will get a warning that there aren't any types, which is correct since we don't provide any for commonjs.
You can add a `@ts-expect-error` directive or switch your config/project to es modules.

**Comment by romainmenke** [comment]
For more context on this change : https://github.com/csstools/postcss-plugins/issues/1031#issuecomment-1848977339

**Comment by doberkofler** [comment]
Thank you!

**Comment by johuhype** [comment]
Hello, i am specifying "type": "module" in package.json and using
"import postcssPresetEnv from 'postcss-preset-env';"
but i am still getting the above mentioned error. Is there something else I need to do tell it that its ES modules?

**Comment by romainmenke** [comment]
Hi @johuhype,

You should check your tsconfig.
You should use `nodeNext` or `node16` for the `module` option.

https://www.typescriptlang.org/docs/handbook/modules/theory.html#the-module-output-format

There might be other issues or configs that are needed, but that is the most common source of issues that I know of.

**Comment by johuhype** [comment]
That was fast. Thanks for the information!
